### ISSUE TITLE
Encoding broken on some strings

### ISSUE THREAD

**Issue by skatenerd** [remvee/clj-base64#1]
In Clojure 1.5.1, I get the following:

`(decode-str (encode-str "abcdefg")) ; => "abcdefd"`

Also, it seems to be removing trailing characters from output:
`(decode-str (encode-str "abcdefg\n")) ; => "abcdefg"`

**Comment by skatenerd** [comment]
Everything seems to work consistently when the string's length is divisible by 3.

**Comment by remvee** [comment]
Can't reproduce.
